name: Discord Notifications 

on: workflow_dispatch

jobs:
  checkForContent:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Project Board
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: | 
            const result = await github.projects.getCard({
              card_id: 56801078,
            });
            const issueData = await github.request(result.content_url)
            console.log(issueData.data)


#   notifcation:
#     needs: ['checkForContent']
#     runs-on: ubuntu-latest
#     steps:
#       - name: Discord notification
#         env:
#           DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#         uses: Ilshidur/action-discord@master
#         with:
#           args: 'Hello World'
