name: Discord Notifications 

on: workflow_dispatch

jobs:
  checkForContent:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Project Board
        uses: actions/github-script@v3
        id: set-result
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: | 
            const execa = require(`${process.env.GITHUB_WORKSPACE}/node_modules/fs`)

            const result = await github.projects.getCard({
              card_id: 56801078,
            });

            const issue = await github.request(result.data.content_url)
            fs.writeFileSync('result.json', issue);
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: issue-data
          path: result.json
  

#   notifcation:
#     needs: ['checkForContent']
#     runs-on: ubuntu-latest
#     steps:
#       - name: Discord notification
#         env:
#           DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#         uses: Ilshidur/action-discord@master
#         with:
#           args: 'Hello World'
