name: Discord Notifications 

on: workflow_dispatch

jobs:
  check-for-live-content:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Project Board
        uses: actions/github-script@v3
        id: set-result
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: | 
            const fs = require('fs')

            const result = await github.projects.getCard({
              card_id: 56801078,
            });

            const issue = await github.request(result.data.content_url)
            fs.writeFileSync('result.json', JSON.stringify(issue));
      - name: Upload issue artifact
        uses: actions/upload-artifact@v2
        with:
          name: issue-data
          path: result.json
  

  send-discord-notifcation:
    needs: ['check-for-live-content']
    runs-on: ubuntu-latest
    steps:
      - name: Download issue artifact
        uses: actions/download-artifact@v2
        with:
          name: issue-data
      - name: Print the final result
        id: data
        shell: bash
        run: |
          ISSUE_TITLE="$(jq '.data.title' result.json)"
          echo $ISSUE_TITLE
          
          echo ::set-output name=title::${ISSUE_TITLE}
          echo "ISSUE_TITLE=${ISSUE_TITLE}" >> GITHUB_ENV
      - name: Set environment variables
        run: |
          echo "PR_TITLE=[Test] Add report file $(date +%d-%m-%Y)" >> $GITHUB_ENV
          echo "PR_BODY=This PR was auto-generated on $(date +%d-%m-%Y) by [create-pull-request](https://github.com/peter-evans/create-pull-request)." >> $GITHUB_ENV
      - name: Just print stuff
        run: |
          echo $ISSUE_TITLE
          echo ${{ steps.data.outputs.title }}
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Hello World [this is a test], ${{ steps.data.outputs.title }} is up next for streaming'
