name: Discord Notifications 

on: workflow_dispatch

jobs:
  checkForContent:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Project Board
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
           const query = `query {
                repository(name: "live", owner: "bdougie") {
                  project(number: 1) {
                    id
                    name
                    columns(last: 1) {
                      edges {
                        node {
                          id
                          name
                          cards(first: 1) {
                            edges {
                              node {
                                id
                                state
                                note
                                content {
                                  ... on Issue {
                                    id
                                    title
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            `; 

            const result = await github.graphql(query)
            console.log(result)


  notifcation:
    needs: ['checkForContent']
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Hello World'
